#!/bin/bash
numOfFiles=$( ls -1 | wc -l )
for (( i=1; i<$numOfFiles + 1; ++i )) ; do
   fileName="$( ls -1 | head -"$i" | tail -1 )"
   if [[ $fileName == *".mp3" ]] ; then
	   artistDir=${fileName%" -"*}
 	   mp3File=${fileName#*"- "}
		mkdir -p "$artistDir"
	   mv "$fileName" "$mp3File"
		mv -i "$mp3File" "$artistDir"
   fi
done
exit 0
