#!/bin/bash
numOfFiles=$( ls -1 | wc -l )
fileRenamed=false
for (( i=1; i<$numOfFiles + 1; ++i )) ; do
   fileName="$( ls -1 | head -"$i" | tail -1 )"
	if [[ $fileName == *"${1}" ]] && [[ ${1} != "" ]] \
	&& [[ ${2} != "" ]] ; then 
		mv "$fileName" ${fileName/%${1}/${2}}
		fileRenamed=true
	fi
done
if [[ $fileRenamed == false ]] ; then
	echo -e 'No file extension(s) match the 1st argument,' \
		'or the 1st or 2nd argument is empty.'
fi
exit 0

